
---
- hosts: test-servers
  gather_facts: no
  remote_user: root
  become: true
  become_method: sudo -s
  tasks:
   - name: replacing config file
     copy:
       src: /vagrant/test.txt
       dest: /etc/httpd/conf/
