
---
- hosts: test-servers
  gather_facts: no
  remote_user: root
  become: yes
  become_method: sudo
  tasks:
   - name: replacing config file
     copy:
       src: /vagrant/test.txt
       dest: /etc/httpd/conf/
